# Generated by Django 2.2.10 on 2020-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('artists', '0002_auto_20200311_1234'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='artists.Artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_songs',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to='songs.Song'),
        ),
    ]
