# Generated by Django 2.2.10 on 2020-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
