# Generated by Django 2.2.10 on 2020-03-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_auto_20200311_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lyrics', models.CharField(max_length=10000)),
                ('audio_url', models.CharField(max_length=1000)),
                ('audio_preview_url', models.CharField(max_length=1000)),
                ('release_year', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.Artist')),
                ('categories', models.ManyToManyField(blank=True, related_name='songs', to='songs.SongCategory')),
            ],
        ),
    ]
